-- Migration 011: Attendance System Tables
-- Creates tables for attendance codes and student submissions

-- Table: attendance_codes
-- Stores codes generated by instructors
CREATE TABLE IF NOT EXISTS attendance_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  batch_id UUID NOT NULL REFERENCES batches(id) ON DELETE CASCADE,
  code VARCHAR(10) NOT NULL UNIQUE,
  generated_by UUID NOT NULL REFERENCES users(id),
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  valid_until TIMESTAMPTZ NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: attendance_submissions
-- Tracks which students submitted which codes
CREATE TABLE IF NOT EXISTS attendance_submissions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  attendance_code_id UUID NOT NULL REFERENCES attendance_codes(id) ON DELETE CASCADE,
  student_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  batch_id UUID NOT NULL REFERENCES batches(id) ON DELETE CASCADE,
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Prevent duplicate submissions (same student can't submit same code twice)
  UNIQUE(attendance_code_id, student_id)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_attendance_codes_batch ON attendance_codes(batch_id);
CREATE INDEX IF NOT EXISTS idx_attendance_codes_code ON attendance_codes(code);
CREATE INDEX IF NOT EXISTS idx_attendance_codes_valid_until ON attendance_codes(valid_until);
CREATE INDEX IF NOT EXISTS idx_attendance_submissions_student ON attendance_submissions(student_id);
CREATE INDEX IF NOT EXISTS idx_attendance_submissions_batch ON attendance_submissions(batch_id);
CREATE INDEX IF NOT EXISTS idx_attendance_submissions_code ON attendance_submissions(attendance_code_id);

-- Trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_attendance_codes_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_attendance_codes_timestamp
  BEFORE UPDATE ON attendance_codes
  FOR EACH ROW
  EXECUTE FUNCTION update_attendance_codes_updated_at();

-- Comments for documentation
COMMENT ON TABLE attendance_codes IS 'Attendance codes generated by instructors (6-char alphanumeric, 3-day validity)';
COMMENT ON TABLE attendance_submissions IS 'Student attendance submissions (tracks who submitted which code)';
COMMENT ON COLUMN attendance_codes.code IS 'Unique 6-character alphanumeric code (e.g., A3X9K2)';
COMMENT ON COLUMN attendance_codes.valid_until IS 'Code expires after this timestamp (3 days from generation)';
COMMENT ON COLUMN attendance_codes.is_active IS 'Instructor can manually deactivate codes';
